### ISSUE TITLE
Consider using SharedPreferences insted of DB

### ISSUE THREAD

**Issue by Kuchto47** [Kuchto47/CustomTimeAlarm#20]
What if we used shared preferences instead of DB for storing (Alarm class should then extend/implement Parcelable)... i just let it sink here, think about what is more efficient...use our DB and build AsyncTasks around it to work with it, or rewrite... I don't care to be honest...

**Comment by jurajvandor** [comment]
SharedPreferences can only store string values or set of strings so we would need to somehow serialize our alarm object to string (probably gson). We should probably stick to DB since we have it working.

**Comment by Kuchto47** [comment]
Deal ;)
