### ISSUE TITLE
Refactor and change layout of AlarmSetFragment

### ISSUE THREAD

**Issue by jurajvandor** [Kuchto47/CustomTimeAlarm#37]
-refactor onCreate() code
-layout and information shown is not sufficient, should be a lot more user friendly

**Comment by jurajvandor** [comment]
add default alarm time (if everything fails) and add date so alarm doesnt skip a day when trafffic changes

**Comment by jurajvandor** [comment]
also we should remove bike from travelling modes

**Comment by Kuchto47** [comment]
suhlasim, a zapracovat #43

**Comment by jurajvandor** [comment]
#43 done

**Comment by jurajvandor** [comment]
#42 done
and this one done
