### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by Kuchto47** [Kuchto47/CustomTimeAlarm#41]
bed time + gtfo

**Comment by Kuchto47** [comment]
Otazka: gtfo sme zahodili? mam pocit ze som ju uz nevidel v nastaveniach (a nepamatam si)... @jurajvandor 

musim tu este doriesit obrazok notifikacie z nejakeho dovodu mi ho tam nedalo aj ked som nastavil :(

**Comment by jurajvandor** [comment]
hej zahodil som to teraz v poslednom commite co siel do mastra
