### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by jurajvandor** [Kuchto47/CustomTimeAlarm#47]
refactor code (mainly SetAlarmFragment)

**Comment by Kuchto47** [comment]
backend more or less done, packages left to refactor:
- activities
- fragments
- adapters
- views

**Comment by jurajvandor** [comment]
backend should check null pointers (in googleApi)

**Comment by Kuchto47** [comment]
hmm? pozeram na kod a v api nevidim kde by som co este checkoval... ??

**Comment by jurajvandor** [comment]
responseBody.results[0] mas viac krat pouzite a este som zabudol ti napisat tie stringy by mali byt asi final co si definujes

**Comment by Kuchto47** [comment]
ok so stringami...
a co sa toho prveho tyka, mal som za to ze ked je to vnutri try tak ak to je nullObject.results[0] tak ma to akurat vyhodi do catchu... a to je v poriadku...nie je to tak? o.O (hladam na googli, este je moznost uzavret inicializaciu responsebody do zvlast trycatch a pracovat s nim v druhom trycatch :D)

**Comment by jurajvandor** [comment]
Však stačí keď dáš of responsebody != null a to isté tie ďalšie veci nie? Načo try. 
A povedal by som ze asi by si nemal nechať kód co môže hodiť null ptr ak to nieje nejaký nevalidny vstup (proste by si to mal podľa mňa kontrolovať)

**Comment by Kuchto47** [comment]
ved...som to tak spravil :D je to v #56
