### ISSUE TITLE
Implement TimeHelper class

### ISSUE THREAD

**Issue by Kuchto47** [Kuchto47/CustomTimeAlarm#7]
Potrebujeme classu ktora nejak rozumne spracuje cas najblizsieho budiku do formatu sekund od 1.1.1970 00:00:00 UTC...

Suggestion: Pockame na implementaciu settingov, ako to bude ukladat, mozno nam to celkom ulahci pracu

**Comment by jurajvandor** [comment]
i think https://developer.android.com/reference/java/util/GregorianCalendar is enough for now (reopen if we need it for something)
